Origin/correcoes
012Jamesson/Atividade pull request #1
Opened 2020-05-07 19:11 UTC by 012Jamesson

correções:
sempre colocar o javascript não essencial no final do <body>
não deixar o css sendo baixado de um cdn, é melhor baixar o arquivo e deixar dentro de alguma pasta na sua aplicação.
na tag <head> naõ se coloca <div> ela é para metatags.
provalvemente você queria utilizar a tag <header>, mas esta fica dentro de <body>
não se usa <br />. O ideal é estilizar com flex, margin, padding, etc.
não se usa estilo inline style=" margin-left: 8%;". Isto é uma má prática.
não se usa &nbsp; ideal é estilizar no css.
tag <input> não se fecha com </input> se usa assim <input .... .. .. . . />

#home.js
se atentar para identação do código.
se atentar para identação do código.
linha 1 - colocar "var" no início das variáveis para declará-las.
linha 17 - não se faz comparação com == sempre com === (estudar a diferença)
linha 24 - na tag img, sempre passar o atributo alt.
linha 25 - style inline não é indicado. criar uma classe.
linha 44 - vc pega a variável 'ul' mas nunca a utiliza. poderia remover.
linha 48 - NUNCA declarar variável com nome 'a', 'b'.
linha 61 - style inline não é indicado. criar uma classe.
linha 66, 78 - sempre comparar com ===
Você criou praticamente 3 funções com a mesma funcionalidade - filtrar. Não faria mais sentido filtrar em uma única função ?
linha 95,98 - evitar o uso de alerts, a experiência do usuário é ruim. Tente apresentar a mensagem de uma forma amigável ao usuário.
linha 94 - não é bom ficar usando indice da forma que está sendo feita. "user-1" se torna ilegível
linha 113, 116 - não deixar console.log na aplicação.

2020-05-07 20:20 UTC, pedropnaves requested changes

2020-05-07 20:20 UTC, pedropnaves commented on home.js
>      temporalUsers =[]
var temporalUsers = []

2020-05-07 20:20 UTC, pedropnaves commented on home.js
> +    alert("esse usuario já se encontra em Lixeira")
Utilizar popup aqui!

2020-05-07 20:20 UTC, pedropnaves commented on home.js
> +    alert("esse usuario já se encontra em Atendidos")
Utilizar popup aqui!

2020-05-07 20:20 UTC, pedropnaves commented on home.js
> +  let user = users.find(item => item.id == id );
comparação sempre com ===

2020-05-07 20:20 UTC, pedropnaves commented on user/user.js
> +}, false);
Dá uma olhada no pseudo-elemento :hover do css!

2020-05-07 20:20 UTC, pedropnaves commented on user/user.js
> +    }, );
Dá uma olhada no pseudo-elemento :hover do css!

2020-05-07 20:20 UTC, pedropnaves commented on user/user.js
> +    }, );
Dá uma olhada no pseudo-elemento :hover do css!

2020-05-07 20:20 UTC, pedropnaves commented on user/user.js
> +    }, );
Dá uma olhada no pseudo-elemento :hover do css!

2020-05-07 20:20 UTC, pedropnaves commented on user/user.js
> +    }, );
Dá uma olhada no pseudo-elemento :hover do css!

2020-05-07 20:20 UTC, pedropnaves commented on user/user.js
> +    }, );
Dá uma olhada no pseudo-elemento :hover do css!

2020-05-11 18:12 UTC, rafamsilva commented
1 - alinhar conteúdo do menu a esquerda, na mesma linha da logo
2 - dar espaçamento maior entre os itens do menu e entre os ícones
3 - O negrito só é aplicado quando o item está selecionado, quando não estiver é sem negrito
4 - label é para representar legenda de campos, eles não devem ser usados sozinhos, deve-se usar somente com inputs, como o menu é uma lista deve-se usar ul e li
5 - arrumar identação
6 - aumentar altura do campo de busca
7 - diminuir o icone de avatar do header
8 - colocar sombra no header
9 - colocar cursor pointer nos itens do menu e nos itens dos cards, isso é para dizer ao usuario que aquele campo tem alguma interação
10 - no user.html trocar de label para div tambem
11 - em vez de criar listeners no js para um elemento, criar uma função e chamar ela direto no html. Ex.: 
<i id='nome' onmouseover="nomedafuncao()" class='far fa-user w3-xxlarge '></i>
. Fazer isso para todos os eventListeners

2020-05-20 13:41 UTC, closed without merging